passing_cases = [
    ("eosinophilic", "pink"),
    ("basophilic", "bluish purple"),
    ("pleomorphic", "variable shape"),
    ("fluke", "trematode"),
    ("spiral bacilli", "S-shaped bacillus"),
    (
        "numerous multicolored bruises",
        "multiple bruises in various stages of healing",
    ),
    (
        "ovoid diplococci in chain-like arrangements",
        "chains of elliptical-shape spheres",
    ),
    ("myocardial infarction", "heart attack"),
    ("cerebrovascular accident", "stroke"),
    ("hypertension", "high blood pressure"),
    ("hypotension", "low blood pressure"),
    ("tachycardia", "rapid heartbeat"),
    ("bradycardia", "slow heart rate"),
    ("arrhythmia", "irregular heartbeat"),
    ("angina pectoris", "chest pain from reduced heart blood flow"),
    ("cardiomegaly", "enlarged heart"),
    ("congestive heart failure", "weak heart with fluid buildup"),
    ("peripheral edema", "swelling of the hands or feet"),
    ("cyanosis", "bluish skin discoloration"),
    ("palpitations", "feeling the heart pounding"),
    ("syncope", "fainting"),
    ("orthostatic hypotension", "blood pressure drop when standing"),
    ("dyspnea", "shortness of breath"),
    ("tachypnea", "rapid breathing"),
    ("apnea", "stopped breathing"),
    ("hemoptysis", "coughing up blood"),
    ("productive cough", "cough bringing up mucus"),
    ("sputum", "coughed-up phlegm"),
    ("rhinorrhea", "runny nose"),
    ("nasal congestion", "stuffy nose"),
    ("pharyngitis", "sore inflamed throat"),
    ("pneumonia", "lung infection"),
    ("pulmonary edema", "fluid in the lungs"),
    ("pleural effusion", "fluid around the lung"),
    ("pneumothorax", "collapsed lung due to air in the chest"),
    ("asthma exacerbation", "asthma flare-up"),
    ("bronchodilator", "medicine that opens the airways"),
    ("hypoxemia", "low oxygen in the blood"),
    ("hypoxia", "insufficient oxygen reaching tissues"),
    ("acute respiratory distress", "sudden severe difficulty breathing"),
    ("cephalgia", "headache"),
    ("migraine with aura", "severe headache preceded by visual warning signs"),
    ("vertigo", "spinning sensation"),
    ("paresthesia", "pins and needles sensation"),
    ("anesthesia", "loss of sensation"),
    ("paresis", "partial paralysis"),
    ("hemiplegia", "paralysis of one side of the body"),
    ("seizure", "convulsion"),
    ("altered mental status", "change in awareness or thinking"),
    ("delirium", "acute fluctuating confusion"),
    ("dementia", "progressive loss of memory and thinking ability"),
    ("aphasia", "difficulty using or understanding language"),
    ("dysarthria", "slurred speech from impaired muscle control"),
    ("ataxia", "poor coordination and unsteady movement"),
    ("tinnitus", "ringing in the ears"),
    ("diplopia", "double vision"),
    ("photophobia", "light sensitivity"),
    ("pruritus", "itching"),
    ("urticaria", "hives"),
    ("ecchymosis", "bruise"),
    ("petechiae", "tiny pinpoint spots of bleeding under the skin"),
    ("erythema", "skin redness"),
    ("pallor", "unusually pale skin"),
    ("jaundice", "yellowing of the skin and eyes"),
    ("diaphoresis", "heavy sweating"),
    ("alopecia", "hair loss"),
    ("dermatitis", "skin inflammation"),
    ("cellulitis", "bacterial infection of deeper skin"),
    ("laceration", "jagged cut"),
    ("abrasion", "superficial scrape"),
    ("contusion", "bruise from blunt trauma"),
    ("pressure ulcer", "bedsore"),
    ("purulent drainage", "pus-like discharge"),
    ("hematemesis", "vomiting blood"),
    ("melena", "black tarry stool from digested blood"),
    ("hematochezia", "bright red blood in stool"),
    ("emesis", "vomiting"),
    ("nausea", "feeling sick to the stomach"),
    ("dysphagia", "difficulty swallowing"),
    ("odynophagia", "painful swallowing"),
    ("dyspepsia", "indigestion"),
    ("gastroesophageal reflux", "acid reflux"),
    ("abdominal distension", "bloated abdomen"),
    ("constipation", "infrequent difficult bowel movements"),
    ("diarrhea", "frequent loose stools"),
    ("steatorrhea", "fatty greasy stool"),
    ("ascites", "fluid buildup in the abdomen"),
    ("hepatomegaly", "enlarged liver"),
    ("splenomegaly", "enlarged spleen"),
    ("cholelithiasis", "gallstones"),
    ("nephrolithiasis", "kidney stones"),
    ("dysuria", "painful urination"),
    ("hematuria", "blood in the urine"),
    ("polyuria", "excessive urination"),
    ("oliguria", "low urine output"),
    ("anuria", "no urine output"),
    ("nocturia", "waking at night to urinate"),
    ("urinary incontinence", "loss of bladder control"),
    ("urinary retention", "inability to empty the bladder"),
    ("urinary tract infection", "bladder or urinary infection"),
    ("renal insufficiency", "reduced kidney function"),
    ("acute kidney injury", "sudden decline in kidney function"),
    ("hyperglycemia", "high blood sugar"),
    ("hypoglycemia", "low blood sugar"),
    ("diabetes mellitus", "chronic high blood sugar disease"),
    ("goiter", "enlarged thyroid gland"),
    ("hyperthyroidism", "overactive thyroid"),
    ("hypothyroidism", "underactive thyroid"),
    ("febrile", "having a fever"),
    ("pyrexia", "elevated body temperature"),
    ("rigors", "violent chills with shivering"),
    ("malaise", "general feeling of illness"),
    ("fatigue", "persistent tiredness"),
    ("cachexia", "severe disease-related weight and muscle loss"),
    ("anorexia", "loss of appetite"),
    ("dehydration", "too little fluid in the body"),
    ("sepsis", "life-threatening organ dysfunction from infection"),
    ("bacteremia", "bacteria in the bloodstream"),
    ("nosocomial infection", "hospital-acquired infection"),
    ("iatrogenic injury", "harm caused by medical treatment"),
    ("benign neoplasm", "noncancerous tumor"),
    ("malignant neoplasm", "cancerous tumor"),
    ("metastasis", "cancer spread to a distant site"),
    ("carcinoma in situ", "localized preinvasive cancer"),
    ("biopsy", "removal of tissue for examination"),
    ("idiopathic", "of unknown cause"),
    ("congenital", "present at birth"),
    ("bilateral", "on both sides"),
    ("unilateral", "on one side"),
    ("proximal", "closer to the trunk"),
    ("distal", "farther from the trunk"),
    ("subcutaneous", "beneath the skin"),
    ("intramuscular", "within a muscle"),
    ("intravenous", "into a vein"),
    ("oral administration", "taken by mouth"),
    ("nil per os", "nothing by mouth"),
    ("as needed", "when required"),
    ("twice daily", "two times a day"),
    ("contraindicated", "should not be used"),
    ("adverse effect", "unwanted medication side effect"),
    ("analgesic", "pain reliever"),
    ("antipyretic", "fever-reducing medicine"),
    ("anticoagulant", "blood thinner"),
    ("diuretic", "water pill"),
    ("antiemetic", "medicine that prevents nausea and vomiting"),
    ("antimicrobial", "drug that kills or inhibits microbes"),
    ("bactericidal", "kills bacteria"),
    ("bacteriostatic", "stops bacteria from multiplying"),
    ("sterile", "free of living microorganisms"),
    ("gram-positive cocci", "purple-staining spherical bacteria"),
    ("fracture", "broken bone"),
    ("comminuted fracture", "bone broken into several pieces"),
    ("dislocation", "bone displaced from its joint"),
    ("sprain", "stretched or torn ligament"),
    ("strain", "stretched or torn muscle or tendon"),
    ("arthralgia", "joint pain"),
    ("myalgia", "muscle pain"),
    ("osteoporosis", "loss of bone density"),
    ("range of motion", "extent a joint can move"),
    ("non-weight-bearing", "do not put weight on the limb"),
    ("complete blood count", "blood cell count panel"),
    ("leukocytosis", "high white blood cell count"),
    ("leukopenia", "low white blood cell count"),
    ("thrombocytopenia", "low platelet count"),
    ("anemia", "low red blood cells or hemoglobin"),
    ("polycythemia", "excess red blood cells"),
    ("electrocardiogram", "heart electrical tracing"),
    ("computed tomography", "CT scan"),
    ("magnetic resonance imaging", "MRI scan"),
    ("ultrasonography", "ultrasound imaging"),
    ("radiolucent", "appears dark on an X-ray"),
    ("radiopaque", "appears white on an X-ray"),
    ("ipsilateral", "on the same side"),
    ("contralateral", "on the opposite side"),
]

failing_cases = [
    ("basophilic", "red"),
    ("basophilic", "pink"),
    ("basophilic", "pinkish red"),
    ("hypotonic", "tight muscle"),
    ("hypertension", "low blood pressure"),
    ("hypotension", "high blood pressure"),
    ("tachycardia", "slow heart rate"),
    ("bradycardia", "rapid heartbeat"),
    ("regular heart rhythm", "irregular heartbeat"),
    ("cardiomegaly", "normal-sized heart"),
    ("cyanosis", "normal pink skin color"),
    ("syncope", "fully conscious throughout"),
    ("orthostatic hypotension", "blood pressure rises when standing"),
    ("dyspnea", "breathing comfortably"),
    ("tachypnea", "slow breathing"),
    ("apnea", "normal spontaneous breathing"),
    ("hemoptysis", "cough without blood"),
    ("productive cough", "dry cough"),
    ("nasal congestion", "clear nasal passages"),
    ("pneumonia", "healthy uninfected lungs"),
    ("pulmonary edema", "lungs without fluid"),
    ("pleural effusion", "no pleural fluid"),
    ("pneumothorax", "fully expanded lung"),
    ("bronchodilation", "airway constriction"),
    ("hypoxemia", "normal blood oxygen level"),
    ("hypoxia", "adequate tissue oxygenation"),
    ("migraine with aura", "headache without aura"),
    ("vertigo", "stable sense of balance"),
    ("paresthesia", "normal sensation"),
    ("anesthesia", "intact sensation"),
    ("paresis", "full muscle strength"),
    ("hemiplegia", "normal movement on both sides"),
    ("seizure", "no seizure activity"),
    ("altered mental status", "alert and fully oriented"),
    ("delirium", "stable clear thinking"),
    ("dementia", "normal cognition"),
    ("aphasia", "fluent intact language"),
    ("dysarthria", "clear speech"),
    ("ataxia", "coordinated steady gait"),
    ("tinnitus", "no ringing in the ears"),
    ("diplopia", "single vision"),
    ("photophobia", "normal tolerance of bright light"),
    ("pruritus", "no itching"),
    ("urticaria", "skin without hives"),
    ("ecchymosis", "unbruised skin"),
    ("petechiae", "skin without pinpoint hemorrhages"),
    ("erythema", "no skin redness"),
    ("pallor", "normal skin color"),
    ("jaundice", "normal skin and scleral color"),
    ("diaphoresis", "dry skin without sweating"),
    ("alopecia", "normal hair growth"),
    ("dermatitis", "healthy noninflamed skin"),
    ("cellulitis", "uninfected skin"),
    ("laceration", "intact unbroken skin"),
    ("abrasion", "no superficial skin injury"),
    ("purulent drainage", "clear nonpurulent drainage"),
    ("epistaxis", "no nasal bleeding"),
    ("hematemesis", "vomiting without blood"),
    ("melena", "normal brown stool"),
    ("hematochezia", "stool without visible blood"),
    ("emesis", "no vomiting"),
    ("nausea", "no stomach sickness"),
    ("dysphagia", "swallowing normally"),
    ("odynophagia", "painless swallowing"),
    ("gastroesophageal reflux", "no acid regurgitation"),
    ("abdominal distension", "flat nondistended abdomen"),
    ("constipation", "frequent loose stools"),
    ("diarrhea", "hard infrequent stool"),
    ("steatorrhea", "normally formed nonfatty stool"),
    ("ascites", "no abdominal fluid"),
    ("hepatomegaly", "normal liver size"),
    ("splenomegaly", "normal spleen size"),
    ("cholelithiasis", "gallbladder without stones"),
    ("nephrolithiasis", "kidneys without stones"),
    ("dysuria", "painless urination"),
    ("hematuria", "urine without blood"),
    ("polyuria", "low urine output"),
    ("oliguria", "excessive urine output"),
    ("anuria", "normal urine production"),
    ("nocturia", "sleeping through the night without urinating"),
    ("urinary incontinence", "full bladder control"),
    ("urinary retention", "complete bladder emptying"),
    ("urinary tract infection", "sterile urinary tract"),
    ("renal insufficiency", "normal kidney function"),
    ("acute kidney injury", "stable renal function"),
    ("hyperglycemia", "low blood sugar"),
    ("hypoglycemia", "high blood sugar"),
    ("goiter", "normal-sized thyroid"),
    ("hyperthyroidism", "underactive thyroid"),
    ("hypothyroidism", "overactive thyroid"),
    ("febrile", "without a fever"),
    ("afebrile", "having a fever"),
    ("pyrexia", "normal body temperature"),
    ("rigors", "no chills or shivering"),
    ("fatigue", "energetic and well rested"),
    ("cachexia", "healthy body weight and muscle mass"),
    ("anorexia", "normal appetite"),
    ("dehydration", "adequate hydration"),
    ("sepsis", "localized infection without organ dysfunction"),
    ("nosocomial infection", "community-acquired infection"),
    ("benign neoplasm", "malignant tumor"),
    ("malignant neoplasm", "noncancerous tumor"),
    ("metastatic cancer", "localized cancer"),
    ("carcinoma in situ", "invasive carcinoma"),
    ("positive biopsy", "negative biopsy"),
    ("congenital condition", "acquired condition"),
    ("bilateral weakness", "weakness on one side only"),
    ("unilateral pain", "pain on both sides"),
    ("proximal muscle weakness", "distal muscle weakness"),
    ("subcutaneous injection", "intravenous injection"),
    ("intramuscular injection", "oral administration"),
    ("nil per os", "unrestricted oral intake"),
    ("scheduled medication", "medication only as needed"),
    ("twice daily", "once daily"),
    ("contraindicated", "recommended for use"),
    ("analgesic", "pain-inducing agent"),
    ("antipyretic", "fever-producing substance"),
    ("anticoagulant", "promotes blood clotting"),
    ("antiemetic", "induces vomiting"),
    ("bactericidal", "only inhibits bacterial growth"),
    ("bacteriostatic", "directly kills bacteria"),
    ("sterile", "contaminated with microorganisms"),
    ("gram-positive cocci", "gram-negative bacilli"),
    ("fracture", "intact bone"),
    ("dislocation", "joint in normal alignment"),
    ("sprain", "uninjured ligament"),
    ("strain", "uninjured muscle and tendon"),
    ("arthralgia", "pain-free joints"),
    ("myalgia", "pain-free muscles"),
    ("osteoporosis", "normal bone density"),
    ("non-weight-bearing", "full weight-bearing"),
    ("leukocytosis", "low white blood cell count"),
    ("leukopenia", "high white blood cell count"),
    ("thrombocytopenia", "high platelet count"),
    ("anemia", "elevated hemoglobin"),
    ("polycythemia", "low red blood cell count"),
    ("radiolucent lesion", "radiopaque lesion"),
    ("acute onset", "chronic longstanding course"),
    ("worsening symptoms", "improving symptoms"),
    ("positive test result", "negative test result"),
    ("responsive to treatment", "refractory to treatment"),
    ("stable condition", "rapidly deteriorating condition"),
]
